name: Fetch Latest Releases

on:
  workflow_dispatch:

jobs:
  update_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest releases
        run: |
          mkdir -p external/releases
          curl -s https://api.github.com/repos/daynix/UsbDk/releases/latest | \
          grep "browser_download_url" | cut -d '"' -f 4 | while IFS= read -r url; do
            wget -N -P external/releases "$url"
          done

          curl -s https://api.github.com/repos/bkerler/mtkclient/releases/latest | \
          grep "browser_download_url" | cut -d '"' -f 4 | while IFS= read -r url; do
            wget -N -P external/releases "$url"
          done

      - name: Commit and push if updated
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add external/releases
          git diff --quiet && git diff --staged --quiet || (git commit -m "Updated UsbDk and mtkclient releases" && git push)
